<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
require_once get_template_directory() . '/inc/platform-service-renderer.php';

payroll_render_platform_service_page( [
	'title'            => 'Xero Software Services | Xero Bookkeeping, Accounting & Migration',
	'meta_description' => 'Professional Xero Software Services including Xero Bookkeeping Services, Xero Accounting Solutions, Xero Cloud Accounting, Xero Certified Advisor support, and Xero Migration Services.',
	'footer_copy'      => 'Professional Xero bookkeeping, accounting, cloud accounting, migration, reconciliation, payroll, reporting, and support services.',
	'intro'            => 'Managing your business finances is easier with Xero, but technical issues, setup challenges, and accounting questions can slow down your workflow. Accounting Assist Pro provides professional Xero support services for efficient accounting.',
	'hero'             => [ 'eyebrow' => 'Xero Services', 'icon' => 'fa-solid fa-x', 'heading' => 'Expert Xero Assistance, When You Need It', 'subheading' => 'Empowering businesses with expert Xero solutions for smarter financial management and long-term success.', 'bullets' => [ 'Certified Xero Accounting Experts', 'Fast Issue Resolution', 'Accurate Cloud Bookkeeping', 'Secure Data Management' ], 'stat' => 'Xero', 'stat_label' => 'Cloud accounting support', 'images' => [ [ 'src' => 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?q=80&w=700&auto=format&fit=crop', 'alt' => 'Xero accounting reports and bookkeeping records' ], [ 'src' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=700&auto=format&fit=crop', 'alt' => 'Cloud accounting dashboard' ], [ 'src' => 'https://images.unsplash.com/photo-1556761175-4b46a572b786?q=80&w=700&auto=format&fit=crop', 'alt' => 'Business team using Xero accounting support' ] ] ],
	'offer'            => [ 'heading' => 'Our Xero Accounting & Bookkeeping Services', 'copy' => 'We provide complete bookkeeping and accounting solutions using Xero.', 'cards' => [ [ 'icon' => 'fa-solid fa-book', 'title' => 'Daily Bookkeeping', 'copy' => 'Maintain accurate financial records with professional transaction recording and account management.', 'items' => [] ], [ 'icon' => 'fa-solid fa-building-columns', 'title' => 'Bank & Credit Card Reconciliation', 'copy' => 'Reconcile bank accounts quickly while identifying discrepancies before they become larger issues.', 'items' => [] ], [ 'icon' => 'fa-solid fa-file-invoice-dollar', 'title' => 'Accounts Payable & Receivable', 'copy' => 'Track invoices, vendor payments, customer balances, and outstanding receivables efficiently.', 'items' => [] ], [ 'icon' => 'fa-solid fa-money-check-dollar', 'title' => 'Payroll Assistance', 'copy' => 'Manage employee payroll, salary records, deductions, and payroll reporting with confidence.', 'items' => [] ], [ 'icon' => 'fa-solid fa-chart-line', 'title' => 'Financial Reporting', 'copy' => 'Generate customized Profit & Loss, Balance Sheet, Cash Flow, and General Ledger reports.', 'items' => [] ], [ 'icon' => 'fa-solid fa-compass', 'title' => 'Xero Financial Management', 'copy' => 'Improve budgeting, expense tracking, forecasting, and financial management for better business decisions.', 'items' => [] ], [ 'icon' => 'fa-solid fa-right-left', 'title' => 'Xero Migration Services', 'copy' => 'Switch to Xero with a smooth and secure transfer of your accounting data.', 'items' => [] ] ] ],
	'industries'       => payroll_platform_industries( 'Industries We Serve', 'Our Xero bookkeeping services are suitable for businesses across multiple industries.' ),
	'why'              => [ 'heading' => 'Why Businesses Choose Us?', 'copy' => 'Our Xero accounting solutions help businesses automate financial processes while maintaining complete visibility over accounts.', 'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000&auto=format&fit=crop', 'image_alt' => 'Xero cloud accounting dashboard on laptop', 'items' => [ 'Experienced Xero Accounting Experts', 'Personalized accounting solutions', 'Fast issue resolution', 'Secure cloud accounting support', 'Accurate bookkeeping assistance', 'Reliable financial reporting', 'Dedicated customer support', 'Business-focused accounting guidance' ] ],
	'process'          => [ 'heading' => 'Our Xero Accounting Process', 'copy' => 'A simple process for setup, assessment, resolution, optimization, and ongoing accounting support.', 'steps' => [ [ 'title' => 'Consultation', 'copy' => 'We understand your accounting requirements, software setup, and business goals.' ], [ 'title' => 'Assessment', 'copy' => 'We review your Xero setup, configuration, and data to recommend the right approach.' ], [ 'title' => 'Resolution & Optimization', 'copy' => 'We resolve technical or bookkeeping issues while optimizing your Xero account.' ], [ 'title' => 'Ongoing Support', 'copy' => 'Receive bookkeeping assistance, financial reporting, monitoring, and expert guidance.' ] ] ],
	'testimonials'     => [ [ 'initials' => 'BD', 'name' => 'Brielle Donovan', 'role' => 'Financial Controller', 'quote' => 'AccountingAssistPro made our Xero migration effortless. The transition was smooth, and our team was up and running without disruption.' ], [ 'initials' => 'GE', 'name' => 'Grant Ellison', 'role' => 'Operations Manager', 'quote' => 'Their Xero bookkeeping support helped us clean up reconciliations and streamline monthly reporting.' ], [ 'initials' => 'MK', 'name' => 'Marissa Kensington', 'role' => 'Business Owner', 'quote' => 'From setup to reporting support, AccountingAssistPro has become a trusted accounting partner for our business.' ] ],
	'cta'              => [ 'heading' => "Let's Talk", 'copy' => 'Speak with a Xero expert and get reliable support for bookkeeping, migration, payroll, reports, or setup.', 'button' => 'Speak with a Xero Expert' ],
	'faqs'             => [ [ 'q' => 'What are Xero Bookkeeping Services?', 'a' => 'Xero Bookkeeping Services include daily transactions, bank reconciliations, invoicing, reporting, payroll support, and maintaining accurate records in Xero.' ], [ 'q' => 'What are Xero Migration Services?', 'a' => 'Xero Migration Services transfer accounting data from another platform or spreadsheets into Xero while preserving accuracy and continuity.' ], [ 'q' => 'What are Xero Support Services?', 'a' => 'Xero Support Services help businesses manage setup, bookkeeping, payroll, reconciliation, reporting, and troubleshooting.' ], [ 'q' => 'Do you provide Xero Bookkeeping Assistance?', 'a' => 'Yes. We offer bookkeeping, transaction management, bank reconciliation, financial reporting, and account maintenance.' ], [ 'q' => 'Can you help migrate my business to Xero?', 'a' => 'Yes. We provide migration from QuickBooks, Sage, Zoho Books, Tally, Excel, and other accounting platforms.' ], [ 'q' => 'Is Xero suitable for small businesses?', 'a' => 'Yes. Xero is designed for startups, freelancers, and growing businesses that need cloud accounting and real-time visibility.' ] ],
] );
